// <auto-generated />
using System;
using AdSetSolution.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdSetSolution.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240822012717_CreateAndInsertSeeds")]
    partial class CreateAndInsertSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdSetSolution.Domain.Models.Optional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Optionals");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortalType")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.VehicleImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImgs");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.VehicleOptional", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("OptionalId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.HasKey("VehicleId", "OptionalId");

                    b.HasIndex("OptionalId");

                    b.ToTable("VehicleOptional");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.VehiclePackage", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("PortalType")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("VehicleId", "PackageId", "PortalType");

                    b.HasIndex("PackageId");

                    b.ToTable("VehiclePackages");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.VehicleImg", b =>
                {
                    b.HasOne("AdSetSolution.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleImgs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.VehicleOptional", b =>
                {
                    b.HasOne("AdSetSolution.Domain.Models.Optional", "Optional")
                        .WithMany("VehicleOptional")
                        .HasForeignKey("OptionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdSetSolution.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleOptional")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optional");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.VehiclePackage", b =>
                {
                    b.HasOne("AdSetSolution.Domain.Models.Package", "Package")
                        .WithMany("VehiclePackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdSetSolution.Domain.Models.Vehicle", "Vehicle")
                        .WithMany("VehiclePackages")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.Optional", b =>
                {
                    b.Navigation("VehicleOptional");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.Package", b =>
                {
                    b.Navigation("VehiclePackages");
                });

            modelBuilder.Entity("AdSetSolution.Domain.Models.Vehicle", b =>
                {
                    b.Navigation("VehicleImgs");

                    b.Navigation("VehicleOptional");

                    b.Navigation("VehiclePackages");
                });
#pragma warning restore 612, 618
        }
    }
}
