services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: adset_sqlserver_container
    environment:
      MSSQL_SA_PASSWORD: "AdSet123123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge